Utilize native slash command permissions system
RSA-Bots/PandaProtector pull request #91
Opened 2021-07-04 07:46 UTC by TinyPandas

[I] - PermissionTree and PermissionObject
[I] - Utilize native ApplicationCommandPermissionData
[I] - getMemberCommands in Util returning all Slash Commands by perms
[R] - hasPermission field on command

2021-07-04 15:40 UTC, M39a9am3R approved these changes

2021-07-04 21:01 UTC, M39a9am3R approved these changes

2021-07-06 05:04 UTC, cntkillme requested changes

2021-07-06 05:04 UTC, cntkillme commented on src/store/permissions.ts
> +		perms: [
`getState()` in the following set of options will still return undefined, effectively making all the IDs "0".

2021-07-06 05:04 UTC, cntkillme commented on src/util.ts
> +	return getCommands().filter(async command => {
filter and async don't play well together I don't think, we might wanna use map, promise.all, then filter?

2021-07-06 07:36 UTC, cntkillme approved these changes

2021-07-06 07:43 UTC, merged